export const propertyFeatures: { key: string; checked: boolean }[] = [
  { key: 'airConditioning', checked: false },
  { key: 'safeRoom', checked: false },
  { key: 'storageRoom', checked: false },
  { key: 'furnished', checked: false },
  { key: 'accessibleForDisabled', checked: false },
  { key: 'elevator', checked: false },
  { key: 'renovated', checked: false },
  { key: 'windowBars', checked: false },
  { key: 'forRoommates', checked: false },
  { key: 'petsAllowed', checked: false },
  { key: 'kosherKitchen', checked: false },
  { key: 'solarWaterHeater', checked: false },
  { key: 'multiLockDoors', checked: false },
  { key: 'tornadoAirConditioner', checked: false },
];

export const propertyFeaturesOptions: string[] = [
  'מיזוג',
  'ממ"ד',
  'מחסן',
  'ריהוט',
  ' גישה לנכים',
  'מעלית',
  'משופצת',
  'סורגים',
  'לשותפים',
  'חיות מחמד',
  'מטבח כשר',
  'דוד שמש',
  'דלתות רב-בריח',
  'מזגן טורנדו',
];

export const propertyFeaturesImagesUrls: string[] = [
  'cold-svgrepo-com',
  'cube-escape-svgrepo-com',
  'inventory_2',
  'drawers-svgrepo-com',
  'accessibility-svgrepo-com',
  'elevator-svgrepo-com',
  'paint-svgrepo-com',
  'grid-svgrepo-com',
  'people-svgrepo-com',
  'dog-bold-svgrepo-com',
  'tap-faucet-svgrepo-com',
  'solar-battery-4-svgrepo-com',
  'sensor_door',
  'cold-svgrepo-com',
];
