export type LastsearchesModel = {
  id: string;
  userId: string | null;
  creationDate: string;
  hourOfCreation: number;
  dayOfCreation: number;
  monthOfCreation: number;
  yearOfCreation: number;
  forSale: boolean;
  forRent: boolean;
  moshavOrKibuutz: boolean;
  assetType: string | null;
  minRooms: number;
  maxRooms: number;
  minPrice: number;
  maxPrice: number;
  hasImmediateEntry: boolean;
  hasAccessibleForDisabled: boolean;
  hasAirConditioner: boolean;
  hasExclusivity: boolean;
  hasBolcony: boolean;
  haswindowBars: boolean;
  hasElevator: boolean;
  minFloor: number;
  maxFloor: number;
  forRoommates: boolean;
  hasFurnished: boolean;
  hasPrivateParking: boolean;
  petsAllowed: boolean;
  hasPrice: boolean;
  hasImage: boolean;
  isRenovated: boolean;
  hasSafeRoom: boolean;
  minSquareSize: number;
  maxSquareSize: number;
  hasStorageRoom: boolean;
};
